import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.scss";
import ListItems from '../components/CreditCards/ListItems'
import { AppContext } from "next/app";
import { ApiInstances } from '../types/apiInstance.type'
const inter = Inter({ subsets: ["latin"] });

const Home = ({ cards }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles['card-list']}>
          <h1 className='h1-title'>Your cards</h1>
          <p>Add, Edit or Delete your cards any time</p>
          <ListItems data={cards.cards} />
        </div>
      </main>
    </>
  )
}

Home.getInitialProps = async (context: AppContext, client: { get: (arg: string) => Promise<{ data: ApiInstances; }> | { data: ApiInstances; }; }) => {
  const { data } = await client.get('/cards')
  return { cards: data };
};

export default Home
